[backend] 알림기능 구현
minibeit/minibeit pull request #253
Opened 2021-10-31 15:08 UTC by Gyuchool

#217

2021-11-01 03:52 UTC, donup3 requested changes

2021-11-01 03:52 UTC, donup3 commented on backend/src/main/java/com/minibeit/user/domain/User.java
> +
alarm class로 옮기는 게 좋아보이네요 그리고 if else문이 너무 많은 것 같아요...ㅋㅋ 메서드도 좀 줄일 수 있어보이네요~!

2021-11-01 03:52 UTC, donup3 commented on backend/src/main/java/com/minibeit/user/service/UserService.java
> +
알람이 있는지 보여주는 api 인 것 같은데 user.approvedAlarmOnOff() ,  user.rejectedAlarmOnOff() 메서드 이름들이 알람이 꺼지는 의미라 헷갈리는 것 같아요

2021-11-01 03:52 UTC, donup3 commented on backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepository.java
> +    void updateReject(@Param("applicantIdList") List<Long> applicantIdList,@Param("status") ApplyStatus status);
@Param 안써도 작동하는데 쓰신 이유가 있을까요??

2021-11-01 04:46 UTC, Gyuchool commented on backend/src/main/java/com/minibeit/user/service/UserService.java
> +
approvedAlarmCheck() 이런식으로 바꿀까하는데 괜찮을까요?

2021-11-01 04:48 UTC, Gyuchool commented on backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepository.java
> +    void updateReject(@Param("applicantIdList") List<Long> applicantIdList,@Param("status") ApplyStatus status);
이게 저도 예전엔 됬었는데 어제 돌리다가 아래 에러처럼 나오더라고요
![image](https://user-images.githubusercontent.com/60054318/139623004-db0e8936-a281-459e-9541-2b854c1c8f28.png)
찾아보니 java8버전에서 나오는거라던데 정확한 원인은 아직 못찾았는데 @Parm을 붙여야 에러가 안나오더라고요

2021-11-01 04:50 UTC, Gyuchool commented on backend/src/main/java/com/minibeit/user/domain/User.java
> +
alarm이 null일떄 체크해야해서 user로 가져왔긴 했는데 한번 alarm에서 수정해볼게요!

2021-11-01 04:53 UTC, donup3 commented on backend/src/main/java/com/minibeit/user/service/UserService.java
> +
네네 그리고 알람 관련 역할들은 알람 클래스로 책임을 주는게 좋아보여요

2021-11-01 06:07 UTC, Gyuchool commented on backend/src/main/java/com/minibeit/user/service/UserService.java
> +
알람 클래스에서 처리하라는 말일까요?

2021-11-02 09:01 UTC, donup3 approved these changes

2021-11-02 09:08 UTC, merged